services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.8.1
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 
  kafka:
    image: bitnamilegacy/kafka:3.5.1
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
       # Kafka escuta em todas as interfaces do container
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # Kafka anuncia o IP do seu Mac (substitua abaixo pelo IP da sua rede)
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.22:9092
    depends_on:
      - zookeeper
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
      MSSQL_PID: "Express"
 
  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
 
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
 
networks:
  default:
    name: mydockernetwork