version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.9
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    command: >
      bash -c "
        /opt/bitnami/scripts/kafka/run.sh &
        sleep 10 &&
        kafka-topics.sh --create --if-not-exists --topic SocialMediaPostEvents --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
        tail -f /dev/null
      "